package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Achievement generated by hbm2java
 */
public class Achievement implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date time;
	private String introduce;
	private String filedir;

	public Achievement() {
	}

	public Achievement(String name, Date time, String introduce, String filedir) {
		this.name = name;
		this.time = time;
		this.introduce = introduce;
		this.filedir = filedir;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getIntroduce() {
		return this.introduce;
	}

	public void setIntroduce(String introduce) {
		this.introduce = introduce;
	}

	public String getFiledir() {
		return this.filedir;
	}

	public void setFiledir(String filedir) {
		this.filedir = filedir;
	}

}
