package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book implements java.io.Serializable {

	private Integer id;
	private String name;
	private Date bytime;
	private String num;
	private String addr;

	public Book() {
	}

	public Book(String name, Date bytime) {
		this.name = name;
		this.bytime = bytime;
	}

	public Book(String name, Date bytime, String num, String addr) {
		this.name = name;
		this.bytime = bytime;
		this.num = num;
		this.addr = addr;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBytime() {
		return this.bytime;
	}

	public void setBytime(Date bytime) {
		this.bytime = bytime;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

}
