package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Hardware generated by hbm2java
 */
public class Hardware implements java.io.Serializable {

	private Integer id;
	private String name;
	private String type;
	private String function;
	private String info;
	private Date bytime;
	private int number;
	private String addr;

	public Hardware() {
	}

	public Hardware(String name, String type, String function, String info, Date bytime, int number, String addr) {
		this.name = name;
		this.type = type;
		this.function = function;
		this.info = info;
		this.bytime = bytime;
		this.number = number;
		this.addr = addr;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	public Date getBytime() {
		return this.bytime;
	}

	public void setBytime(Date bytime) {
		this.bytime = bytime;
	}

	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	public String getAddr() {
		return this.addr;
	}

	public void setAddr(String addr) {
		this.addr = addr;
	}

}
