package com.bestksl.domain;
// Generated 2017-4-11 18:52:15 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Hengxiang generated by hbm2java
 */
public class Hengxiang implements java.io.Serializable {

	private Integer id;
	private String name;
	private String number;
	private String persion;
	private Date begintime;
	private Date endtime;
	private String funds;
	private String members;
	private String hetongfang;
	private String finish;
	private String interprate;
	private String filedir;

	public Hengxiang() {
	}

	public Hengxiang(String name, String number, String persion, Date begintime, Date endtime, String funds,
			String members, String hetongfang, String finish, String interprate, String filedir) {
		this.name = name;
		this.number = number;
		this.persion = persion;
		this.begintime = begintime;
		this.endtime = endtime;
		this.funds = funds;
		this.members = members;
		this.hetongfang = hetongfang;
		this.finish = finish;
		this.interprate = interprate;
		this.filedir = filedir;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getPersion() {
		return this.persion;
	}

	public void setPersion(String persion) {
		this.persion = persion;
	}

	public Date getBegintime() {
		return this.begintime;
	}

	public void setBegintime(Date begintime) {
		this.begintime = begintime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getFunds() {
		return this.funds;
	}

	public void setFunds(String funds) {
		this.funds = funds;
	}

	public String getMembers() {
		return this.members;
	}

	public void setMembers(String members) {
		this.members = members;
	}

	public String getHetongfang() {
		return this.hetongfang;
	}

	public void setHetongfang(String hetongfang) {
		this.hetongfang = hetongfang;
	}

	public String getFinish() {
		return this.finish;
	}

	public void setFinish(String finish) {
		this.finish = finish;
	}

	public String getInterprate() {
		return this.interprate;
	}

	public void setInterprate(String interprate) {
		this.interprate = interprate;
	}

	public String getFiledir() {
		return this.filedir;
	}

	public void setFiledir(String filedir) {
		this.filedir = filedir;
	}

}
