package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

/**
 * Literature generated by hbm2java
 */
public class Literature implements java.io.Serializable {

	private Integer id;
	private String name;
	private String author;
	private String from_;
	private String num;
	private String filedir;

	public Literature() {
	}

	public Literature(String name, String author) {
		this.name = name;
		this.author = author;
	}

	public Literature(String name, String author, String from_, String num, String filedir) {
		this.name = name;
		this.author = author;
		this.from_ = from_;
		this.num = num;
		this.filedir = filedir;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getFrom_() {
		return this.from_;
	}

	public void setFrom_(String from_) {
		this.from_ = from_;
	}

	public String getNum() {
		return this.num;
	}

	public void setNum(String num) {
		this.num = num;
	}

	public String getFiledir() {
		return this.filedir;
	}

	public void setFiledir(String filedir) {
		this.filedir = filedir;
	}

}
