package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Paper generated by hbm2java
 */
public class Paper implements java.io.Serializable {

	private Integer id;
	private String name;
	private String author;
	private String teacher;
	private Date time;
	private String type;
	private String mettingname;
	private String juanheqi;
	private String qishiyema;
	private String wenzhangbianhao;
	private String jiansuohao;
	private String filedir;

	public Paper() {
	}

	public Paper(String name, String author, String teacher, Date time) {
		this.name = name;
		this.author = author;
		this.teacher = teacher;
		this.time = time;
	}

	public Paper(String name, String author, String teacher, Date time, String type, String mettingname,
			String juanheqi, String qishiyema, String wenzhangbianhao, String jiansuohao, String filedir) {
		this.name = name;
		this.author = author;
		this.teacher = teacher;
		this.time = time;
		this.type = type;
		this.mettingname = mettingname;
		this.juanheqi = juanheqi;
		this.qishiyema = qishiyema;
		this.wenzhangbianhao = wenzhangbianhao;
		this.jiansuohao = jiansuohao;
		this.filedir = filedir;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getTeacher() {
		return this.teacher;
	}

	public void setTeacher(String teacher) {
		this.teacher = teacher;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getMettingname() {
		return this.mettingname;
	}

	public void setMettingname(String mettingname) {
		this.mettingname = mettingname;
	}

	public String getJuanheqi() {
		return this.juanheqi;
	}

	public void setJuanheqi(String juanheqi) {
		this.juanheqi = juanheqi;
	}

	public String getQishiyema() {
		return this.qishiyema;
	}

	public void setQishiyema(String qishiyema) {
		this.qishiyema = qishiyema;
	}

	public String getWenzhangbianhao() {
		return this.wenzhangbianhao;
	}

	public void setWenzhangbianhao(String wenzhangbianhao) {
		this.wenzhangbianhao = wenzhangbianhao;
	}

	public String getJiansuohao() {
		return this.jiansuohao;
	}

	public void setJiansuohao(String jiansuohao) {
		this.jiansuohao = jiansuohao;
	}

	public String getFiledir() {
		return this.filedir;
	}

	public void setFiledir(String filedir) {
		this.filedir = filedir;
	}

}
