package com.bestksl.domain;
// Generated 2016-6-5 13:59:52 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String name;
	private String password;
	private int permission;
	private Set<Message> messages = new HashSet<Message>(0);

	public User() {
	}

	public User(String name, String password, int permission) {
		this.name = name;
		this.password = password;
		this.permission = permission;
	}

	public User(String name, String password, int permission, Set<Message> messages) {
		this.name = name;
		this.password = password;
		this.permission = permission;
		this.messages = messages;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public int getPermission() {
		return this.permission;
	}

	public void setPermission(int permission) {
		this.permission = permission;
	}

	public Set<Message> getMessages() {
		return this.messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
