package com.bestksl.domain;
// Generated 2017-4-13 15:43:01 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Zongxiang generated by hbm2java
 */
public class Zongxiang implements java.io.Serializable {

	private Integer id;
	private String fromm;
	private String xmtype;
	private String hdtype;
	private String ssxk;
	private String kcname;
	private String number;
	private String person;
	private Date begin;
	private Date end;
	private String funds;
	private String realfunds;
	private String zzxs;
	private String hzxs;
	private String ktzcy;
	private String stunumber;
	private String situation;
	private String finish;
	private Date endtime;
	private String cddw;
	private String cgdjh;
	private String filedir;

	public Zongxiang() {
	}

	public Zongxiang(String fromm, String xmtype, String hdtype, String ssxk, String kcname, String number,
			String person, Date begin, Date end, String funds, String realfunds, String zzxs, String hzxs, String ktzcy,
			String stunumber, String situation, String finish, Date endtime, String cddw, String cgdjh,
			String filedir) {
		this.fromm = fromm;
		this.xmtype = xmtype;
		this.hdtype = hdtype;
		this.ssxk = ssxk;
		this.kcname = kcname;
		this.number = number;
		this.person = person;
		this.begin = begin;
		this.end = end;
		this.funds = funds;
		this.realfunds = realfunds;
		this.zzxs = zzxs;
		this.hzxs = hzxs;
		this.ktzcy = ktzcy;
		this.stunumber = stunumber;
		this.situation = situation;
		this.finish = finish;
		this.endtime = endtime;
		this.cddw = cddw;
		this.cgdjh = cgdjh;
		this.filedir = filedir;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getFromm() {
		return this.fromm;
	}

	public void setFromm(String fromm) {
		this.fromm = fromm;
	}

	public String getXmtype() {
		return this.xmtype;
	}

	public void setXmtype(String xmtype) {
		this.xmtype = xmtype;
	}

	public String getHdtype() {
		return this.hdtype;
	}

	public void setHdtype(String hdtype) {
		this.hdtype = hdtype;
	}

	public String getSsxk() {
		return this.ssxk;
	}

	public void setSsxk(String ssxk) {
		this.ssxk = ssxk;
	}

	public String getKcname() {
		return this.kcname;
	}

	public void setKcname(String kcname) {
		this.kcname = kcname;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getPerson() {
		return this.person;
	}

	public void setPerson(String person) {
		this.person = person;
	}

	public Date getBegin() {
		return this.begin;
	}

	public void setBegin(Date begin) {
		this.begin = begin;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public String getFunds() {
		return this.funds;
	}

	public void setFunds(String funds) {
		this.funds = funds;
	}

	public String getRealfunds() {
		return this.realfunds;
	}

	public void setRealfunds(String realfunds) {
		this.realfunds = realfunds;
	}

	public String getZzxs() {
		return this.zzxs;
	}

	public void setZzxs(String zzxs) {
		this.zzxs = zzxs;
	}

	public String getHzxs() {
		return this.hzxs;
	}

	public void setHzxs(String hzxs) {
		this.hzxs = hzxs;
	}

	public String getKtzcy() {
		return this.ktzcy;
	}

	public void setKtzcy(String ktzcy) {
		this.ktzcy = ktzcy;
	}

	public String getStunumber() {
		return this.stunumber;
	}

	public void setStunumber(String stunumber) {
		this.stunumber = stunumber;
	}

	public String getSituation() {
		return this.situation;
	}

	public void setSituation(String situation) {
		this.situation = situation;
	}

	public String getFinish() {
		return this.finish;
	}

	public void setFinish(String finish) {
		this.finish = finish;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	public String getCddw() {
		return this.cddw;
	}

	public void setCddw(String cddw) {
		this.cddw = cddw;
	}

	public String getCgdjh() {
		return this.cgdjh;
	}

	public void setCgdjh(String cgdjh) {
		this.cgdjh = cgdjh;
	}

	public String getFiledir() {
		return this.filedir;
	}

	public void setFiledir(String filedir) {
		this.filedir = filedir;
	}

}
